plugins:
  # Strip lint/vale comments and drop everything after <!-- internal -->
  './lib/remark-osiolabs-strip-internal':
  './lib/retext-osiolabs-rules':
  remark-preset-lint-recommended:
  preset-lint-markdown-style-guide:
  # We use double-dashes in filenames
  remark-lint-no-file-name-consecutive-dashes: false
  # We don't wrap lines of text based on length.
  lint-maximum-line-length: false
  # We have some custom tags like [# summary #] which aren't valid Markdown.
  remark-lint-no-undefined-references: false
  remark-lint-no-shortcut-reference-link: false
  # This is more subjective than objective.
  remark-lint-no-duplicate-headings: false
  lint-no-empty-url:
  lint-final-newline:
  # We use _ instead of * for emphasis because that's what Prettier does.
  remark-lint-emphasis-marker: '_'
  remark-validate-links:
  remark-lint-no-dead-urls:

# These settings are used when you use remark to output formatted Markdown.
settings:
  bullet: '-'
  emphasis: '_'
  strong: '*'
  fence: '`'
  fences: true
  incrementListMarker: false
  listItemIndent: 1
